apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: zelawat27/test_api:latest
          env:
            - name: INGRESS_URL
              value: ingress:8080
          ports:
            - containerPort: 8090
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 100m

---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api # Selecting pods with label "app=myapp"
  ports:
    - protocol: TCP
      port: 8090 # Port on the Service
      targetPort: 8090 # Port on the Pod (deployment)
