apiVersion: apps/v1
kind: Deployment
metadata:
  name: message
  labels:
    app: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - name: ingress
          image: nats-streaming:linux
          ports:
            - containerPort: 4222
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 100m

---
apiVersion: v1
kind: Service
metadata:
  name: message
spec:
  selector:
    app: message # Selecting pods with label "app=myapp"
  ports:
    - protocol: TCP
      port: 4222 # Port on the Service
      targetPort: 4222 # Port on the Pod (deployment)
