apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-deployment
  labels:
    app: ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingress
  template:
    metadata:
      labels:
        app: ingress
