apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
  labels:
    app: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress
  template:
    metadata:
      labels:
        app: ingress
